name: retack
description: Flutter SDK to handle API calls to retack.ai for posting exceptions & errors 
version: 0.0.1
homepage: https://retack.ai

environment:
  sdk: '>=3.0.0 <4.0.0'
  

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.16.0
