name: retack
description: A Dart Package to handle API calls for posting exceptions & errors to Retack.AI
version: 0.0.7
homepage: https://retack.ai
repository: https://github.com/truenary/retack_pkg_flutter

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.16.0
